name: Formatting

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Code formatting
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/job-setup
        with:
          install-dependencies: format
      - name: Run import formatter
        run: isort .
      - name: Run code formatter
        run: black .
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply formatting.
