name: Vulnerability Scanning

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Vulnerability scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/job-setup
        with:
          install-dependencies: test
      - name: Run static code scanner
        run: bandit example_python_package -rv
